version: 2

jobs:
  build-bazel:
    docker:
      - image: nixos/nix
    working_directory: ~/sparkle
    environment:
      - NIXRUN: nix-shell --pure --run
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: |
            apk --no-progress update
            apk --no-progress add ca-certificates bash
            nix-channel --update

            # cachix install
            nix-env -if https://github.com/cachix/cachix/tarball/master --substituters https://cachix.cachix.org --trusted-public-keys cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM=
            # XXX Workaround: it complains about no USER, so let set a dummy USER
            USER=dummy cachix use tweag

            # bazel install
            nix-build nixpkgs.nix -A bazel | cachix push tweag

            $NIXRUN "echo nix dependencies installed"
      - run:
          name: Build project
          command: $NIXRUN "bazel build //..."
      - run:
          name: Test hello example
          command: |
              $NIXRUN "bazel run hello-java"
              $NIXRUN "bazel run clotestbin"
              $NIXRUN "bazel run clotestbin-cc"
              $NIXRUN "bazel run clotestbin-cc-norunfiles"
              $NIXRUN "bazel run clotestbin-cc-pie"

workflows:
  version: 2
  build:
    jobs:
      - build-bazel:
          context: org-global
