version: 2

jobs:
  build-bazel:
    docker:
      - image: nixos/nix
    working_directory: ~/sparkle
    environment:
      - NIXRUN: nix-shell -I nixpkgs=./nixpkgs.nix -p gcc bazel --run
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: |
            apk update --no-progress && apk --no-progress add ca-certificates bash binutils zip unzip
            $NIXRUN "echo nix dependencies installed"
      - run:
          name: Build project
          command: $NIXRUN "bazel build  --jobs 2 //..."
      - run:
          name: Test hello example
          command: |
              $NIXRUN "bazel run --jobs 2 hello-java"
              $NIXRUN "bazel run --jobs 2 clotestbin"

workflows:
  version: 2
  build:
    jobs:
      - build-bazel
