version: 2

# NOTE:
#   Disk cache:
#       We don't want to keep old artifacts around so we always build from
#       scratch on master builds and upload the new cache afterwards. Because
#       Circle doesn't allow skipping a "restore_cache" we create a dummy
#       "empty" cache that's only ever pulled on master. Alternatively we could
#       ask Bazel to clean up old items (LRU style):
#           https://docs.bazel.build/versions/master/remote-caching.html
#       It also appears that there's ongoing work but the feature is not ready:
#           https://github.com/bazelbuild/bazel/issues/5139

jobs:
  build-darwin:
    macos:
      xcode: "12.5.0"
    steps:
      - run:
          name: Checkout
          command: |
            git --version
            git clone -n https://github.com/tweag/clodl.git .
            git checkout $CIRCLE_SHA1

      - run:
          name: Install Nix
          command: |
            sh <(curl -L https://nixos.org/nix/install) --darwin-use-unencrypted-nix-store-volume

      - run:
          name: Install cachix
          shell: /bin/bash -eilo pipefail
          command: |
            nix-env -iA cachix -f https://github.com/NixOS/nixpkgs/tarball/46113713d4f25579e07b78116a61ab6f178f4153

      - run:
          name: Run cachix
          shell: /bin/bash -eilo pipefail
          command: |
            cachix use tweag
            cachix watch-store tweag
          background: true

      - run:
          name: Configure
          command: |
            mkdir -p ~/.cache/bazel/
            echo build --host_platform=@io_tweag_rules_nixpkgs//nixpkgs/platforms:host > .bazelrc.local

      - restore_cache:
          keys: # see note about 'Disk cache'
              - v1-clodl-empty-{{ .Branch }}-
              - v1-clodl-cache-{{ .Branch }}-
              - v1-clodl-cache-master-

      - run:
          name: Build all
          shell: /bin/bash -eilo pipefail
          command: |

            # Keep CI awake
            while true; do echo "."; sleep 60; done &

            nix-shell --pure --run 'bazel build //...'
      - run:
          name: Run tests
          shell: /bin/bash -eilo pipefail
          command: |

            nix-shell --pure --run 'bazel run clotestbin'
            nix-shell --pure --run 'bazel run clotestbin-cc'
            nix-shell --pure --run 'bazel run hello-java'

        # see note about 'Disk cache'
      - save_cache:
          key: v1-clodl-cache-{{ .Branch }}-{{ .BuildNum }}
          paths:
              - ~/.cache/bazel/

      - run:
          name: Clean up cache
          shell: /bin/bash -eilo pipefail
          command: |
            rm -rf ~/.cache/bazel/
            mkdir -p ~/.cache/bazel/

      - save_cache:
          key: v1-clodl-empty-master-{{ .BuildNum }}
          paths:
              - ~/.cache/bazel/

workflows:
  version: 2
  build:
    jobs:
      - build-darwin:
          context: org-global # for the cachix token
