name: Build & test
on:
  push:

jobs:
  test:
    name: Run test
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=./nixpkgs.nix
      - name: Run cachix
        run: |
          cachix use tweag &
          cachix watch-store tweag &
      - name: Configure
        run: |
          mkdir -p ~/repo-cache ~/disk-cache
          echo build --host_platform=@io_tweag_rules_nixpkgs//nixpkgs/platforms:host > .bazelrc.local
      - name: Build all
        run: nix-shell --pure --run 'bazel build //... --sandbox_debug --verbose_failures'
      - name: Run tests
        run: |
          nix-shell --pure --run 'bazel run clotestbin'
          nix-shell --pure --run 'bazel run clotestbin-cc'
          nix-shell --pure --run 'bazel run hello-java'
