name: Build & test
on:
  push:

jobs:
  test:
    name: Run test
    runs-on: macos-11
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install NixOS
        uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=./nixpkgs.nix

      - name: Install cachix
        uses: cachix/cachix-action@v10
        with:
          name: tweag

      - name: Run cachix
        run: cachix watch-store tweag &

      - name: Configure
        run: |
          mkdir -p ~/repo-cache ~/disk-cache
          echo build --host_platform=@io_tweag_rules_nixpkgs//nixpkgs/platforms:host > .bazelrc.local

      - name: Build all
        run: nix-shell --pure --run 'bazel build //... --sandbox_debug --verbose_failures'

      - name: Run tests
        run: |
          nix-shell --pure --run 'bazel run clotestbin'
          nix-shell --pure --run 'bazel run clotestbin-cc'
          nix-shell --pure --run 'bazel run hello-java'
